version: '3.8'

services:

  casa-api:
    container_name: casa-api
    depends_on:
      - zookeeper
      - kafka
      - kafka-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URL=jdbc:postgresql://192.168.68.116:5432/casa
      - DB_USER=postgres
      - DD_PASSWORD=postgres