version: '3.8'

services:
  casa-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.68.116:5432/casa
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_ADDRESS=192.168.68.116:9092
    networks:
      - casa-network

networks:
  casa-network:
    driver: bridge 