server:
    port: 8081
    servlet:
        context-path: /casa-api

spring:
    jpa:
        database: POSTGRESQL
        show-sql: false
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: ${SPRING_DATASOURCE_URL}
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    kafka:
        bootstrapServers: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}
        groupId: casa-group
        retry:
            initialInterval: 500
            maxAttempts: 15